// e-commerce-app-react/src/component/CheckOut.tsx
import React, { useState } from 'react';
import { Container, Typography, Box, TextField, Select, MenuItem, Button } from '@mui/material';
import { useAlert } from '../hook/UserAlert';
import { AppDispatch } from '../redux/store';
import { useDispatch } from 'react-redux';
import {clearCart } from '../redux/CartSlice';
import { useNavigate } from 'react-router-dom';
const Checkout: React.FC = () => {
    const showAlert = useAlert();
    const dispatch = useDispatch<AppDispatch>();
    const navigate=useNavigate();

  const [personalDetails, setPersonalDetails] = useState({
    fullName: '',
    email: '',
    address: ''
  });

  const [paymentMethod, setPaymentMethod] = useState('');

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = event.target;
    setPersonalDetails({
      ...personalDetails,
      [name]: value
    });
  };

  const handleSelectChange = (event: React.ChangeEvent<{ value: unknown }>) => {
    setPaymentMethod(event.target.value as string);
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
     resetForm();
    showAlert('successfully CheckOut!', 'success');
    dispatch(clearCart());
    navigate('/products')


  };

  const resetForm = () => {
    setPersonalDetails({
      fullName: '',
      email: '',
      address: ''
    });
    setPaymentMethod('');
  };

  return (
    <Container maxWidth="sm">
      <Box mt={4} p={3} bgcolor="background.paper" boxShadow={2} borderRadius={8}>
        <Typography variant="h5" gutterBottom>
          Checkout
        </Typography>
        <form onSubmit={handleSubmit}>
          <TextField
            label="Full Name"
            variant="outlined"
            fullWidth
            margin="normal"
            name="fullName"
            value={personalDetails.fullName}
            onChange={handleInputChange}
            required
          />
          <TextField
            label="Email Address"
            variant="outlined"
            fullWidth
            margin="normal"
            name="email"
            value={personalDetails.email}
            onChange={handleInputChange}
            required
          />
          <TextField
            label="Address"
            variant="outlined"
            fullWidth
            margin="normal"
            name="address"
            value={personalDetails.address}
            onChange={handleInputChange}
            multiline
            rows={3}
            required
          />
          <Select
            label="Payment Method"
            variant="outlined"
            fullWidth
            value={paymentMethod}
            onChange={(event) => handleSelectChange(event as React.ChangeEvent<{ value: unknown }>)}
            required
          >
            <MenuItem value="" disabled>
              Select Payment Method
            </MenuItem>
            <MenuItem value="creditCard">Credit Card</MenuItem>
            <MenuItem value="paypal">Cash On Delivery</MenuItem>
            <MenuItem value="bankTransfer">Check</MenuItem>
          </Select>
          <Button type="submit" variant="contained" color="primary" fullWidth>
            Place Order
          </Button>
        </form>
      </Box>
    </Container>
  );
};

export default Checkout;

// e-commerce-app-angular/src/app/components/checkout/checkout.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { NgToastService } from 'ng-angular-popup';
import { CartService } from 'src/app/services/cart.service';
import { CookieServices } from 'src/app/services/cookies.service';

@Component({
  selector: 'app-checkout',
  templateUrl: './checkout.component.html',
  styleUrls: ['./checkout.component.css']
})
export class CheckoutComponent {
  constructor(private router: Router,private cookiesService:CookieServices,private cartService:CartService,private tostService:NgToastService ) {}

  personalDetails = {
    fullName: '',
    email: '',
    address: ''
  };

  paymentMethod: string = '';
  creditCardDetails = {
    cardNumber: '',
    expiryDate: '',
    cvv: ''
  };

  onSubmit() {
    this.cartService.clearCart();
    this.resetForm();
    this.tostService.success({
      detail: 'Success',
      summary: "Successfully Place Order!!!!!! ",
      duration: 3000
    })
    this.router.navigate(['products'])
  }

  resetForm() {
    this.personalDetails = {
      fullName: '',
      email: '',
      address: ''
    };
    this.paymentMethod = '';
    this.creditCardDetails = {
      cardNumber: '',
      expiryDate: '',
      cvv: ''
    };
  }
}

<div class="container">
  <div class="checkout-form">
    <h2 class="checkout-heading">Checkout</h2>
    <form (ngSubmit)="onSubmit()" #checkoutForm="ngForm">
      <div class="form-group">
        <label for="fullName">Full Name</label>
        <input type="text" class="form-control" id="fullName" name="fullName" [(ngModel)]="personalDetails.fullName" required>
      </div>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" [(ngModel)]="personalDetails.email" required>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <textarea class="form-control" id="address" name="address" [(ngModel)]="personalDetails.address" rows="3" required></textarea>
      </div>

      <div class="form-group">
        <label for="paymentMethod">Payment Method</label>
        <select class="form-control" id="paymentMethod" name="paymentMethod" [(ngModel)]="paymentMethod" required>
          <option value="" disabled>Select Payment Method</option>
          <option value="creditCard">Credit Card</option>
          <option value="paypal">Cash On Delivery</option>
          <option value="bankTransfer">Check</option>
        </select>
      </div>

      <div *ngIf="paymentMethod === 'creditCard'">
        <div class="form-group">
          <label for="cardNumber">Card Number</label>
          <input type="text" class="form-control" id="cardNumber" name="cardNumber" [(ngModel)]="creditCardDetails.cardNumber" required>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="expiryDate">Expiry Date</label>
            <input type="text" class="form-control" id="expiryDate" name="expiryDate" [(ngModel)]="creditCardDetails.expiryDate" required>
          </div>
          <div class="form-group col-md-6">
            <label for="cvv">CVV</label>
            <input type="text" class="form-control" id="cvv" name="cvv" [(ngModel)]="creditCardDetails.cvv" required>
          </div>
        </div>
      </div>

      <div class="text-center">
        <button type="submit" class="btn btn-primary">Place Order</button>
      </div>
    </form>
  </div>
</div>
