// e-commerce-app-react/src/component/ProductCard.tsx
import React from 'react';
import { Card, CardMedia, CardContent, Typography, CardActions, Button } from '@mui/material';
import { Link } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { addItem } from '../redux/CartSlice';
import Product from '../models/Product';

interface ProductCardProps {
  product: Product;
}

const ProductCard: React.FC<ProductCardProps> = ({ product }) => {
  const dispatch = useDispatch();

  const handleAddToCart = () => {
    dispatch(addItem(product));
  };

  return (
    <Card>
      <CardMedia
        component="img"
        alt={product.name}
        height="100"
        image={`http://localhost:4000/${product.image}`}
      />
      <CardContent>
        <Typography gutterBottom variant="h5" component="div">
          {product.name}
        </Typography>
        <Typography variant="body2" color="text.secondary">
          ${product.price}
        </Typography>
      </CardContent>
      <CardActions>
        <Button size="small" component={Link} to={`/products/${product._id}`}>View Details</Button>
        <Button size="small" onClick={handleAddToCart}>Add to Cart</Button>
      </CardActions>
    </Card>
  );
};

export default ProductCard;

// e-commerce-app-angular/src/app/components/product-card/product-card.component.ts
import { Component, Input } from '@angular/core';
import { Product } from 'src/app/model/product.model';
import { CartService } from 'src/app/services/cart.service';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.css']
})
export class ProductCardComponent {
  @Input() product!:Product;

  constructor(private cartService: CartService) {}

  addToCart(): void {
    this.cartService.addItemToCart(this.product);
  }
}

<div class="product-card">
    <img [src]="'http://localhost:4000/'+product.image" [alt]="product.name" />
    <div class="product-details">
      <h3>{{ product.name }}</h3>
      <p>${{ product.price }}</p>
    </div>
    <div class="actions">
        <button mat-button [routerLink]="'/products/' + product._id" style="color: black;">View Details</button>
      <button mat-button (click)="addToCart()" style="color: black;">Add to Cart</button>
    </div>
  </div>
