// e-commerce-app-react/src/component/Signup.tsx
/**
 * Signup component in this file user register and save data in backend
 */

import React, { useState } from 'react';
import { TextField, Button, Container, Typography, Box } from '@mui/material';
import { registerUser } from '../services/authService';
import { useNavigate } from 'react-router-dom';

const Signup: React.FC = () => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [phone, setPhone] = useState('');
  const navigate = useNavigate();

  /**
   * Handle Register Data form react event and call register user function
   * @param e
   */
  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const response = await registerUser(name, email, password, phone);
      console.log('Registration Successful:', response);
      navigate('/login'); 
    } catch (error) {
      console.error('Registration Failed:', error);
    }
  };

  return (
    <Container maxWidth="sm">
      <Box component="form" onSubmit={handleRegister} mt={8}>
        <Typography variant="h4" gutterBottom>Register</Typography>
        <TextField
          label="Name"
          variant="outlined"
          fullWidth
          margin="normal"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <TextField
          label="Email"
          variant="outlined"
          fullWidth
          margin="normal"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <TextField
          label="Password"
          variant="outlined"
          type="password"
          fullWidth
          margin="normal"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <TextField
          label="Phone"
          variant="outlined"
          fullWidth
          margin="normal"
          value={phone}
          onChange={(e) => setPhone(e.target.value)}
        />
        <Button type="submit" variant="contained" color="primary" fullWidth>Register</Button>
      </Box>
    </Container>
  );
};

export default Signup;

// e-commerce-app-angular/src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent {
  name: string = '';
  email: string = '';
  password: string = '';
  phone: string = '';
  errorMessage: string = '';

  constructor(private authService: AuthService, private router: Router) {}


  
  /**
   * Handle User Data and call api throw services for register user
   */
  async handleRegister(): Promise<void> {
    try {
      const response = await this.authService.register(
        this.name,
        this.email,
        this.password,
        this.phone
      );
      console.log('Registration Successful:', response);
      this.router.navigate(['/products']);
    } catch (error) {
      console.error('Registration Failed:', error);
      this.errorMessage = 'Registration failed. Please try again.';
    }
  }
}

<div class="container">
    <h2>Register</h2>
    <form (ngSubmit)="handleRegister()">
      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" id="name" name="name" class="form-control" [(ngModel)]="name" required>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" id="email" name="email" class="form-control" [(ngModel)]="email" required>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" id="password" name="password" class="form-control" [(ngModel)]="password" required>
      </div>
      <div class="form-group">
        <label for="phone">Phone</label>
        <input type="text" id="phone" name="phone" class="form-control" [(ngModel)]="phone" required>
      </div>
      <button type="submit" class="btn btn-primary">Register</button>
      <p class="text-danger">{{ errorMessage }}</p>
    </form>
  </div>
