// e-commerce-app-angular/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})


export class LoginComponent {
  email: string = '';
  password: string = '';
  errorMessage: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  /**
   * Handle Login Data and call api throw services
   */
  async handleLogin(): Promise<void> {
    try {
      console.log(this.email + this.password);
      const response = await this.authService.loginUser(
        this.email,
        this.password
      );
      console.log('Login Successful:', response);
      this.router.navigate(['/products']);
    } catch (error) {
      console.error('Login Failed:', error);
      this.errorMessage = 'Login failed. Please check your credentials.';
    }
  }
}

<mat-card class="login-container">
  <h2>Login</h2>
  <form [formGroup]="loginForm" (ngSubmit)="handleLogin()">
    <mat-form-field class="full-width">
      <mat-label>Email</mat-label>
      <input matInput type="email" id="email" name="email" formControlName="email" placeholder="Enter your email" required>
      <mat-error *ngIf="loginForm.get('email')?.hasError('required')">Email is required</mat-error>
      <mat-error *ngIf="loginForm.get('email')?.hasError('email')">Please enter a valid email address</mat-error>
    </mat-form-field>
    
    <mat-form-field class="full-width">
      <mat-label>Password</mat-label>
      <input matInput type="password" id="password" name="password" formControlName="password" placeholder="Enter your password" required>
      <mat-error *ngIf="loginForm.get('password')?.hasError('required')">Password is required</mat-error>
    </mat-form-field>
    
    <button type="submit" mat-raised-button color="primary">Login</button>
    <p class="text-danger">{{ errorMessage }}</p>
  </form>
</mat-card>

// e-commerce-app-react/src/component/Login.tsx
/**
 * Login Component
 * 
 * Show Login design and call api
 */

import React, { useState } from 'react';
import { TextField, Button, Container, Typography, Box } from '@mui/material';
import { loginUser } from '../services/authService';
import { useNavigate } from 'react-router-dom';
import { login } from '../redux/UserSlice';
import { useDispatch } from 'react-redux';
import {  AppDispatch } from '../redux/store';
const Login: React.FC = () => {


  const dispatch = useDispatch<AppDispatch>();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  /**
   * get form input data and call loginuser function for call node js api
   * @param event
   */
  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const response = await loginUser(email, password);
      console.log('Login Successful:', response);
      const { _id } = response; 

      dispatch(login(_id));
      navigate("/products");

    } catch (error) {
      console.error('Login Failed:', error);
    }
  };

  return (
    <Container maxWidth="sm">
      <Box component="form" onSubmit={handleLogin} mt={8}>
        <Typography variant="h4" gutterBottom>Login</Typography>
        <TextField
          label="Email"
          variant="outlined"
          fullWidth
          margin="normal"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <TextField
          label="Password"
          variant="outlined"
          type="password"
          fullWidth
          margin="normal"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <Button type="submit" variant="contained" color="primary" fullWidth>Login</Button>
      </Box>
    </Container>
  );
};

export default Login;
